### ISSUE TITLE
conflicting python packages

### ISSUE THREAD

**Issue by DavideConficconi** [Xilinx/PYNQ-ZU#2]
Hello,

I was trying to reproduce the PYNQ-ZU image. 
Unfortunately, I got an error in the building phase that seems related to python packages versions.
Here is the log:

`ERROR: Cannot install -r requirements.txt (line 28), -r requirements.txt (line 4) and plotly==4.5.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested plotly==4.5.2
    dash 0.21.1 depends on plotly
    plotly-express 0.3.1 depends on plotly<4.0.0a0 and >=3.10.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
`

How can I fix this?
Is it related to the installing machine?

Thank  you a lot

**Comment by mariodruiz** [comment]
Hi @DavideConficconi, you can download the SD card image from here https://www.tul.com.tw/ProductsPYNQ-ZU.html

**Comment by schelleg** [comment]
Yes, this is a known issue - it is fixed in the upcoming v2.7 release.  

[Workarounds are here on discuss.pynq.io](https://discuss.pynq.io/t/plotly-dependency-conflict/2143/12), but @mariodruiz is correct that the prebuilt image is the easiest path forward.  Closing now.
